# Site settings
title: Oakdale Boutique
baseurl: ""
url: "http://oakdaleboutique.com"
email: OakdaleBoutique@gmail.com
etsy_username: OakdaleBoutique
facebook_username:  OakdaleBoutique

# Defaults
paginate: 6
per_page: 6

# Build settings
markdown: kramdown
sass:
    style: :compressed
    sass_dir: _sass
